# Change these first
owner: Zombie-Technology # Your GitHub username
repo: uptime # Your Github repository name


# Add your sites here
assignees:
  - l1kw1d
sites: 
  - name: Zombie Graphique Inc
    url: https://zombiegraphique.com
    icon: https://zombiegraphique.com/favicon.ico
    expectedStatusCodes:
    - 200
    - 301
    - 302
  - name: ZombieGraphique CRM
    url: https://crm.zombiegraphique.com
    expectedStatusCodes:
    - 200
    - 301
    - 302
  - name: Hypnose Nancy Gagnon
    url: https://www.hypnonancy.com
    icon: https://hypnonancy.com/favicon.ico
    expectedStatusCodes:
    - 200
    - 301
    - 302
  - name: BardQ.com
    url: https://bardq.com
  - name: BarQ.ca
    url: https://bardq.ca
  - name: beautedesiles.ca
    url: https://beautedesiles.ca/
  - name: Diamand
    url: https://diamand.ca
  - name: DiagDiesel
    url: https://diagdiesel.com
  - name: Eso-sense
    url: https://eso-sense.com
  - name: Groupe JFK
    url: https://groupejfk.ca
  - name: Julio Pizza
    url: https://julio.pizza
    expectedStatusCodes:
    - 200
    - 301
    - 302
  - name: Match PME
    url: https://matchpme.ca
    expectedStatusCodes:
    - 200
    - 301
    - 302
  - name: Willkess Farm  
    url: https://wilkess.farm
    expectedStatusCodes:
    - 200
    - 301
    - 302
  - name: MJReno
    url: https://mjreno.ca
  - name: O Boutte
    url: https://oboutte.ca
  - name: Sheriff Ville
    url: https://sherifville.com
  - name: Sub satori
    url: https://subsatori.com
  - name: Passion saveurs Keto
    url: https://passionsaveursketo.ca
    ########################
  - name: WiFi QR 
    url: https://wifi.pin.plus
    icon: https://wifi.pin.plus/favicon.ico
    
    
status-website:
  theme: dark
  cname: status.zombiegraphique.com
  logoUrl: https://github.com/Zombie-Technology/ZSTMAIN/blob/main/assets/images/logos/logo_red_black.png
  name: ZombieGraphique - Surveillance Web 
  introTitle: Websites status monitoring / Surveillance de votre site web
  introMessage: ZombieGraphique Inc.
  navbar:
    - title: Status | Zombiegraphique Inc.
      href:  https://status.zombiegraphique.com
    - title: Notre site Web
      href: https://zombiegraphique.com
    - title: CRM
      href: https://crm.zombiegraphique.com
    - title: WIFI QR
      href: https://pin.plus/WIFI
